### ISSUE TITLE
decision support agents

### ISSUE THREAD

**Issue by Josephrp** [team-tonic-arena-hacks/Main-Repo#19]

**Comment by Mind-Interfaces** [comment]
https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/financial_support_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/medical_support_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/ethical_support_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/technical_support_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/environmental_support_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/educational_support_agent.nlp

**Comment by Mind-Interfaces** [comment]
Support agents in the house. I'm happy with the looks of those.

Until one of these agents blows out of it's NLP settings, I think this task is complete.

If anyone gets an unexpected response.. open a new ticket. ;p
