### ISSUE TITLE
language agents

### ISSUE THREAD

**Issue by Josephrp** [team-tonic-arena-hacks/Main-Repo#21]

**Comment by Mind-Interfaces** [comment]
https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/language_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/computational_linguistics_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/python_nlp_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/formal_language_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/business_language_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/informal_communication_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/body_language_agent.nlp

**Comment by Mind-Interfaces** [comment]
No god-like Babylonian translator agents.. but we do have effective language agents.

*housekeeping!*
