### ISSUE TITLE
human in the loop feedback system

### ISSUE THREAD

**Issue by Josephrp** [team-tonic-arena-hacks/Main-Repo#37]

**Comment by Mind-Interfaces** [comment]
After humanity's piss-poor show last weekend; I vote, "NO." to prop #37

I'll take it a step further and make it an executive decision.

If you want a loop overseer, talk to one of our agents; case closed.

I know my disappointment is a bit misplaced, dragging my grudges into the git is wrong.. 

but this is the best way I can express myself and how bad of a job I think we are doing as humans.
