### ISSUE TITLE
trained / improved coding agent

### ISSUE THREAD

**Issue by Josephrp** [team-tonic-arena-hacks/Main-Repo#40]

**Comment by Mind-Interfaces** [comment]
https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/c_plus_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/c_sharp_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/go_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/javascript_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/php_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/python_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/r_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/ruby_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/rust_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/sql_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/swift_programming_agent.nlp

https://github.com/team-tonic-arena-hacks/Main-Repo/blob/main/agents/typescript_programming_agent.nlp

**Comment by Mind-Interfaces** [comment]
These agents improve the quality of code by setting the correct language domain and advising suitable standards protocols. 

It also tells these particular coding agents to only use best practices and exemplar code patterns... 

Basically, we told them to focus on a specific language and do our homework the correct way the comp-sci prof expects.

I expect the outputs to be limited in a way by their adherence to known code patterns.

If orchestrated correctly these agents provide the code overview, while more task-specific agents produce the obscure code.


I addressed the top languages that GPT-4 shows the highest proficiency.. 

the domains could be extended by almost a magnitude to 100 agents.

but i think this still covers the real worker bees in the GPT-System well.

as such...

 *gets a running jump start at smashing the close button*
